In [18]:
#write statement to import numpy
import numpy as np

array([1, 2, 3])

In [19]:
#create an array using numpy.
np.array([1,2,3])

array([1, 2, 3])

In [3]:
#create an array of 10 random integers
a=np.random.randint(1,20,8)
a

array([14,  9, 15, 18, 13,  7, 19, 13])

In [4]:
#create an array of elements from 10-20
a=np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [20]:
#crerate an array which contains value 5, 10 times.
a=np.random.randint(5,6,10)
a

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [12]:
#create a one dimensional array and convert that into 3*3 matrix.
a=np.array([10,20,30,40,50,60,70,80,90])
b=a.reshape(3,3)
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [13]:
# Create a 2D array of size 3*3 but all the elements should be btween 0 to 1
a=np.random.rand(3,3)
a

array([[0.32707565, 0.28212384, 0.77599786],
       [0.82411304, 0.1472213 , 0.60339752],
       [0.35148861, 0.79294918, 0.10028425]])

In [15]:
#concatenate 2d array horizontally and verticallly
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [16]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])