# 4. diag ==> This function creates a two dimensional array with all the diagonal elements as the given value and rest are zero

In [1]:
import numpy as np
a=np.diag([1,4,8,9])
a

array([[1, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 9]])

# 5.randint ==> this function is used to generate a random number between a given range.

# syntax==randint(min_value, max_value, total_numbers)

In [3]:
import numpy as np
a=np.random.randint(1,10,3)
a

array([1, 9, 7])

# 6.rand() ==> this function is used to generate a random number between 0 to 1.

# syntax ==rand(number of values)

In [4]:
import numpy as np
a=np.random.rand(6)
a

array([0.97717695, 0.00655922, 0.49155929, 0.59382893, 0.29947139,
       0.79471939])

# 7.randn() ==>this function is used to generate a random number from -3 to close 3.this may return positive or negative as well

# syntax== random.randn(no. of values)

In [5]:
import numpy as np
a=np.random.randn(5)
a

array([ 1.44776634, -1.65486094,  0.08733786, -0.40681207, -0.59185058])

# Reshaping Data

In [7]:
import numpy as np
a=np.random.randint(1,50,12)
a

array([26,  8, 45, 46, 32, 18,  6, 16, 13, 39, 21,  9])

In [8]:
#n(rows)*n(columns)=n(total_elements)

In [9]:
a.shape

(12,)

In [11]:
a=a.reshape(2,6)
a

array([[26,  8, 45, 46, 32, 18],
       [ 6, 16, 13, 39, 21,  9]])

In [12]:
a=a.reshape(6,2)
a

array([[26,  8],
       [45, 46],
       [32, 18],
       [ 6, 16],
       [13, 39],
       [21,  9]])

In [13]:
a=a.reshape(3,4)
a

array([[26,  8, 45, 46],
       [32, 18,  6, 16],
       [13, 39, 21,  9]])

In [14]:
a=a.reshape(4,3)
a

array([[26,  8, 45],
       [46, 32, 18],
       [ 6, 16, 13],
       [39, 21,  9]])

In [16]:
a=a.reshape(12,1)
a

array([[26],
       [ 8],
       [45],
       [46],
       [32],
       [18],
       [ 6],
       [16],
       [13],
       [39],
       [21],
       [ 9]])

In [17]:
import numpy as np
a=np.random.randint(1,100,64)
a

array([55, 97, 89, 53, 58, 81, 74, 88, 31, 62, 95,  2, 37, 16, 30, 45, 59,
       48, 21, 78, 94, 33,  3, 53, 30, 88, 92, 49, 77, 31, 64, 58, 21, 45,
       25, 76, 26, 14, 65, 78, 45, 59, 50, 56, 24, 44,  7, 88, 53, 17, 51,
       34, 73, 95, 37, 13, 51, 41, 10, 55, 54, 60, 26, 91])

In [18]:
a=a.reshape(1,64)
a

array([[55, 97, 89, 53, 58, 81, 74, 88, 31, 62, 95,  2, 37, 16, 30, 45,
        59, 48, 21, 78, 94, 33,  3, 53, 30, 88, 92, 49, 77, 31, 64, 58,
        21, 45, 25, 76, 26, 14, 65, 78, 45, 59, 50, 56, 24, 44,  7, 88,
        53, 17, 51, 34, 73, 95, 37, 13, 51, 41, 10, 55, 54, 60, 26, 91]])

In [19]:
a=a.reshape(64,1)
a

array([[55],
       [97],
       [89],
       [53],
       [58],
       [81],
       [74],
       [88],
       [31],
       [62],
       [95],
       [ 2],
       [37],
       [16],
       [30],
       [45],
       [59],
       [48],
       [21],
       [78],
       [94],
       [33],
       [ 3],
       [53],
       [30],
       [88],
       [92],
       [49],
       [77],
       [31],
       [64],
       [58],
       [21],
       [45],
       [25],
       [76],
       [26],
       [14],
       [65],
       [78],
       [45],
       [59],
       [50],
       [56],
       [24],
       [44],
       [ 7],
       [88],
       [53],
       [17],
       [51],
       [34],
       [73],
       [95],
       [37],
       [13],
       [51],
       [41],
       [10],
       [55],
       [54],
       [60],
       [26],
       [91]])

In [20]:
a=a.reshape(2,32)
a

array([[55, 97, 89, 53, 58, 81, 74, 88, 31, 62, 95,  2, 37, 16, 30, 45,
        59, 48, 21, 78, 94, 33,  3, 53, 30, 88, 92, 49, 77, 31, 64, 58],
       [21, 45, 25, 76, 26, 14, 65, 78, 45, 59, 50, 56, 24, 44,  7, 88,
        53, 17, 51, 34, 73, 95, 37, 13, 51, 41, 10, 55, 54, 60, 26, 91]])

In [21]:
a=a.reshape(32,2)
a

array([[55, 97],
       [89, 53],
       [58, 81],
       [74, 88],
       [31, 62],
       [95,  2],
       [37, 16],
       [30, 45],
       [59, 48],
       [21, 78],
       [94, 33],
       [ 3, 53],
       [30, 88],
       [92, 49],
       [77, 31],
       [64, 58],
       [21, 45],
       [25, 76],
       [26, 14],
       [65, 78],
       [45, 59],
       [50, 56],
       [24, 44],
       [ 7, 88],
       [53, 17],
       [51, 34],
       [73, 95],
       [37, 13],
       [51, 41],
       [10, 55],
       [54, 60],
       [26, 91]])

In [22]:
a=a.reshape(4,16)
a

array([[55, 97, 89, 53, 58, 81, 74, 88, 31, 62, 95,  2, 37, 16, 30, 45],
       [59, 48, 21, 78, 94, 33,  3, 53, 30, 88, 92, 49, 77, 31, 64, 58],
       [21, 45, 25, 76, 26, 14, 65, 78, 45, 59, 50, 56, 24, 44,  7, 88],
       [53, 17, 51, 34, 73, 95, 37, 13, 51, 41, 10, 55, 54, 60, 26, 91]])

In [23]:
a=a.reshape(16,4)
a

array([[55, 97, 89, 53],
       [58, 81, 74, 88],
       [31, 62, 95,  2],
       [37, 16, 30, 45],
       [59, 48, 21, 78],
       [94, 33,  3, 53],
       [30, 88, 92, 49],
       [77, 31, 64, 58],
       [21, 45, 25, 76],
       [26, 14, 65, 78],
       [45, 59, 50, 56],
       [24, 44,  7, 88],
       [53, 17, 51, 34],
       [73, 95, 37, 13],
       [51, 41, 10, 55],
       [54, 60, 26, 91]])

In [24]:
a=a.reshape(8,8)
a

array([[55, 97, 89, 53, 58, 81, 74, 88],
       [31, 62, 95,  2, 37, 16, 30, 45],
       [59, 48, 21, 78, 94, 33,  3, 53],
       [30, 88, 92, 49, 77, 31, 64, 58],
       [21, 45, 25, 76, 26, 14, 65, 78],
       [45, 59, 50, 56, 24, 44,  7, 88],
       [53, 17, 51, 34, 73, 95, 37, 13],
       [51, 41, 10, 55, 54, 60, 26, 91]])

# Principle of -1

In [27]:
# if no.of rows and elements are given then we can find no. of column by putting -1 in place of column and viceversa
a=a.reshape(-1,4)
a

array([[55, 97, 89, 53],
       [58, 81, 74, 88],
       [31, 62, 95,  2],
       [37, 16, 30, 45],
       [59, 48, 21, 78],
       [94, 33,  3, 53],
       [30, 88, 92, 49],
       [77, 31, 64, 58],
       [21, 45, 25, 76],
       [26, 14, 65, 78],
       [45, 59, 50, 56],
       [24, 44,  7, 88],
       [53, 17, 51, 34],
       [73, 95, 37, 13],
       [51, 41, 10, 55],
       [54, 60, 26, 91]])

# Seed Function() ==> We know that randint function generates random numbers.Everytime we run the program ,new set of random number is generated.So to ,solve this problem we use seed() function

In [30]:
import numpy as np
np.random.seed(5)#seed function use krne ke bad vo value change nhi krta hai
a=np.random.randint(1,20,10)
a

array([ 4, 15, 16,  7, 17, 10,  9,  5,  8, 17])

# View Vs Copy ==>when we slice a sub-array from an array,it may be done by two ways

# View

In [31]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80])
b=a[3:6]
b[:]=0
a

array([10, 20, 30,  0,  0,  0, 70, 80])

# Copy

In [34]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80])
b=a[3:6].copy()
b[:]=0
print(a)
print(b)

[10 20 30 40 50 60 70 80]
[0 0 0]


# Conditional selection

In [35]:
import numpy as np
a=np.arange(1,16)#last value exclude krega
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [36]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [37]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [42]:
b=a>10
a[b]

array([11, 12, 13, 14, 15])

In [43]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

# Operations on Array

In [45]:
import numpy as np
a=np.arange(1,5)
a*2

array([2, 4, 6, 8])

In [46]:
a+2

array([3, 4, 5, 6])

In [47]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [48]:
a=np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [49]:
b=np.array([5,6,7,8]).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [50]:
a+b

array([[ 6,  8],
       [10, 12]])

In [51]:
a-b

array([[-4, -4],
       [-4, -4]])

In [52]:
b/a

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [53]:
a*b

array([[ 5, 12],
       [21, 32]])

In [54]:
a.dot(a)#matrix multiplication

array([[ 7, 10],
       [15, 22]])

# Some important functionS in numpy

In [55]:
import numpy as np
a=np.array([10,20,30,40,50])
np.min(a)

10

In [56]:
np.max(a)

50

In [57]:
np.argmin(a)#it will return indexing of minimum value

0

In [58]:
np.argmax(a)

4

In [59]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [60]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

# Linspace()==>this function returns value btween a given range and with a same gap between consecutive elements.

In [61]:
import numpy as np
a=np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

# np.unique(arr,return_index=True,return_counts=True)

# returns 3 array.1.the array with unique values .2.the array with respective index value.3.the array with counting of frequency

In [62]:
a=np.array([10,20,30,40,50])
np.unique(a, return_index =True,return_counts=True)

(array([10, 20, 30, 40, 50]),
 array([0, 1, 2, 3, 4], dtype=int64),
 array([1, 1, 1, 1, 1], dtype=int64))

# horizontal and vertical stacking

In [63]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a

array([1, 2, 3, 4])

In [64]:
b

array([5, 6, 7, 8])

In [65]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [66]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])