# Introduction to numpy

In [ ]:
#introduction to numpy ==>
#why numpy is better than list?
#1). same data type ==>array
#2). memory consume ==> numpy less , list high
#3). computation power ==>numpy high, list less
#4).functions ==> numpy high, list less

In [2]:
import numpy as np

In [1]:
a=[1,23,78,68]
type(a)

list

In [4]:
b=np.array(a)
b

array([ 1, 23, 78, 68])

In [5]:
type(b)

numpy.ndarray

In [3]:
mylist=[]
x=int(input("enter the no.of elements in list"))

for i in range(x):
    y=int(input("enter the elements of list"))
    mylist.append(y)
#print(mylist)
b=np.array(mylist)
b
    
    


enter the no.of elements in list4
enter the elements of list1
enter the elements of list2
enter the elements of list3
enter the elements of list4


array([1, 2, 3, 4])

# how to check shape and size of an array

In [ ]:
#esc+1 shift+enter

In [ ]:
#shape =n(rows), n(columns)

#size= total_elements ==> n(rows)*n(columns)

In [4]:
print("total shape=",b.shape)
print("total size=",b.size)

total shape= (4,)
total size= 4


In [6]:
a=[[1,2,3], [4,5,6], [7,8,9]]
b=np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
print("total shape= ",b.shape)
print("total size= ",b.size)

total shape=  (3, 3)
total size=  9


In [ ]:
#Image ===>pixels ===>(0-255)px ==> 0px(complete black), 255px(white)

#convert ===> gryscale image ==>
#Image(pixels) ===>Normalization(0-1) ===>0px==>black , 1px ==>white

#0, 1==>neuron system
#matrix ==>rows,columns==>
#symetric matrix==.n(rows)=n(columns)
#symetric matrix==.n(rows)!=n(columns)
#diagonal elements=[(1,1),(2,2),(3,3).....(n,n)]


# (1).zeros()===> it will create an array in which all the elements are zero.

In [8]:
a=np.zeros(4)
a

array([0., 0., 0., 0.])

In [10]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# (2).ones()===>it will create an array in which all the values are one

In [13]:
a=np.ones(3)
a

array([1., 1., 1.])

In [14]:
b=np.ones((3,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# (3).eye()===>this function will create an array in which diagonal positional elements are 1 and other are zero

In [16]:
a=np.eye(3,4)#asymetric
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [17]:
a=np.eye(4)#symetric
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])